"""add_workspace_id_to_reads_summaries

Revision ID: f863b56169cf
Revises: 0007
Create Date: 2026-08-07 02:36:07.183345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f863b56169cf'
down_revision: Union[str, Sequence[str], None] = '0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_page_embeddings_page_id'), table_name='page_embeddings')
    op.drop_table('page_embeddings')
    op.drop_index(op.f('idx_crawled_pages_indexed'), table_name='crawled_pages')
    op.drop_index(op.f('idx_crawled_pages_url'), table_name='crawled_pages')
    op.drop_table('crawled_pages')
    op.drop_index(op.f('idx_crawl_jobs_status'), table_name='crawl_jobs')
    op.drop_table('crawl_jobs')
    op.add_column('reading_list', sa.Column('workspace_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_reading_list_workspace_id'), 'reading_list', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'reading_list', 'workspaces', ['workspace_id'], ['id'], ondelete='SET NULL')
    op.add_column('summary_list', sa.Column('workspace_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_summary_list_workspace_id'), 'summary_list', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'summary_list', 'workspaces', ['workspace_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('idx_workspace_items_url'), table_name='workspace_items')
    op.drop_index(op.f('idx_workspace_items_workspace'), table_name='workspace_items')
    op.drop_index(op.f('idx_workspaces_session'), table_name='workspaces')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_workspaces_session'), 'workspaces', ['session_id'], unique=False)
    op.create_index(op.f('idx_workspace_items_workspace'), 'workspace_items', ['workspace_id'], unique=False)
    op.create_index(op.f('idx_workspace_items_url'), 'workspace_items', ['url'], unique=False)
    op.drop_constraint(None, 'summary_list', type_='foreignkey')
    op.drop_index(op.f('ix_summary_list_workspace_id'), table_name='summary_list')
    op.drop_column('summary_list', 'workspace_id')
    op.drop_constraint(None, 'reading_list', type_='foreignkey')
    op.drop_index(op.f('ix_reading_list_workspace_id'), table_name='reading_list')
    op.drop_column('reading_list', 'workspace_id')
    op.create_table('crawl_jobs',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('depth', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'pending'::text"), autoincrement=False, nullable=False),
    sa.Column('claimed_by', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('claimed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('retry_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('crawl_jobs_pkey')),
    sa.UniqueConstraint('url', name=op.f('crawl_jobs_url_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_crawl_jobs_status'), 'crawl_jobs', ['status'], unique=False)
    op.create_table('crawled_pages',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('crawled_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('indexed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('crawled_pages_pkey')),
    sa.UniqueConstraint('url', name=op.f('crawled_pages_url_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_crawled_pages_url'), 'crawled_pages', ['url'], unique=False)
    op.create_index(op.f('idx_crawled_pages_indexed'), 'crawled_pages', ['indexed'], unique=False)
    op.create_table('page_embeddings',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('page_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('chunk_index', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('model', sa.TEXT(), server_default=sa.text("'BGE-small-en-v1.5'::text"), autoincrement=False, nullable=False),
    sa.Column('dimension', sa.INTEGER(), server_default=sa.text('384'), autoincrement=False, nullable=False),
    sa.Column('embedding', postgresql.ARRAY(sa.REAL()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['crawled_pages.id'], name=op.f('page_embeddings_page_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('page_embeddings_pkey')),
    sa.UniqueConstraint('page_id', 'chunk_index', name=op.f('page_embeddings_page_id_chunk_index_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_page_embeddings_page_id'), 'page_embeddings', ['page_id'], unique=False)
    # ### end Alembic commands ###
